version: '3.5'

services:
  typesense:
    image: typesense/typesense:27.0.rc21
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: k8pX5hD0793d8YQC5aD1aEPd7VleSuGP
    volumes:
      - /tmp/typesense-server-data:/data
    ports:
      - "8108:8108"
    restart: 'no'